version: '3.8'
services: 
    mongodb-blog-video:
        image: mongo:latest
        container_name: mongodb-blog-video
        volumes: 
            - mongodb-data:/data/db
        networks: 
            - blog-video-networks
        ports: 
            - 27017:27017
    blog-video-app:
        # build otomatis
        build: .
        # end build otomatis
        container_name: blog-video-app-container
        networks:
            - blog-video-networks
        ports: 
            - 3000:3000
        environment: 
            WAIT_HOSTS: mongo:27017
            # update otomatis
        volumes: 
            - .:/app 
            # update otomatis
networks: 
    blog-video-networks:
volumes: 
    mongodb-data:

   